### ISSUE TITLE
Startup fails with panic: extension ping failed

### ISSUE THREAD

**Issue by zwass** [Uptycs/kubequery#11]
**Describe the bug**
```
kubectl -n kubequery logs kubequery-7b768854-pkrwf
panic: extension ping failed: read unix @->/opt/kubequery/osquery.em: read: connection reset by peer

goroutine 1 [running]:
main.main()
	/home/runner/work/kubequery/kubequery/cmd/kubequery/main.go:57 +0x489
W0124 01:10:59.180693     7 watcher.cpp:557] osqueryd worker respawning too quickly: 1 times
W0124 01:11:05.407027   239 extensions.cpp:781] Required extension not found or not loaded: kubequery
E0124 01:11:05.407080   239 init.cpp:553] An error occurred during extension manager startup: Required extension not found or not loaded: kubequery
I0124 01:11:05.408862   239 events.cpp:867] Event publisher not enabled: BPFEventPublisher: Publisher disabled via configuration
I0124 01:11:05.408974   239 events.cpp:867] Event publisher not enabled: auditeventpublisher: Publisher disabled via configuration
I0124 01:11:05.409005   239 events.cpp:867] Event publisher not enabled: inotify: Publisher disabled via configuration
I0124 01:11:05.409034   239 events.cpp:867] Event publisher not enabled: syslog: Publisher disabled via configuration
```

**To Reproduce**
Apply the provided yaml (https://github.com/Uptycs/kubequery/blob/master/kubequery.yaml) on a Docker Desktop k8s cluster.

**Expected behavior**
Startup succeeds.

**Screenshots**

**Additional context**
latest kubequery image

**Comment by spasam** [comment]
Thanks @zwass . I messed that up. Can you try now. Should be fixed now. I am working on integration tests which hopefully catches these issues. 

I will create a tag version (0.1.0) that is more stable

**Comment by zwass** [comment]
Actually I still see the log like that

```
panic: registering extension: *osquery.ExtensionManagerRegisterExtensionArgs. (0) field write error: write unix @->/opt/kubequery/osquery.em: write: broken pipe

goroutine 1 [running]:
main.main()
	/home/runner/work/kubequery/kubequery/cmd/kubequery/main.go:57 +0x489
W0124 01:30:16.881999     9 extensions.cpp:781] Required extension not found or not loaded: kubequery
```

But querying the `kubernetes deployments` table works! So maybe the logging needs to be adjusted so that there's a retry and it only logs when it fails permanently?

**Comment by spasam** [comment]
Ah let me check the logs and see what is going on. Looks like the extension is failing and watcher is respawing.

Between `autoload`, `extensions` and `extensions_require` flags, I am play around to see what is ideal...

**Comment by zwass** [comment]
Ah, yeah, it looks like the extension keeps going down. I see `Extension respawning too quickly: /usr/bin/kubequery` in the logs.

**Comment by spasam** [comment]
Hmm! Wonder if you file system is read-only.
What kind'a k8s cluster is this? Generic, EKS, GCE...?

**Comment by zwass** [comment]
This is Docker Desktop k8s on macOS.

**Comment by zwass** [comment]
<img width="500" alt="Screen Shot 2021-01-23 at 5 44 52 PM" src="https://user-images.githubusercontent.com/575602/105618976-b3596f00-5da2-11eb-9fd4-f1eeecfb067b.png">

**Comment by spasam** [comment]
Ok. Let me try with that. I have been testing with microk8s and AWS EKS.
I just created a 0.1.0 pre-release: https://github.com/Uptycs/kubequery/releases/tag/0.1.0

Testing with 0.1.0 version in microk8s (and EKS is same). Will try and repro ^^
```
$ mk logs kubequery-6b87cc45dd-npqx8 -n kubequery
I0124 01:43:55.694340    53 interface.cpp:110] Registering extension (kubequery, 5887, version=, sdk=)
I0124 01:43:55.829253     7 events.cpp:867] Event publisher not enabled: BPFEventPublisher: Publisher disabled via configuration
I0124 01:43:55.829313     7 events.cpp:867] Event publisher not enabled: auditeventpublisher: Publisher disabled via configuration
I0124 01:43:55.829321     7 events.cpp:867] Event publisher not enabled: inotify: Publisher disabled via configuration
I0124 01:43:55.829327     7 events.cpp:867] Event publisher not enabled: syslog: Publisher disabled via configuration
```

**Comment by zwass** [comment]
It seems to be up and down, but I am sometimes able to get it responding to queries. I'll let you know if I discover anything more. Stability with extensions can be tricky.

**Comment by spasam** [comment]
:( Let me see if I can repro. Is it the same below error for all crashes?
```
panic: registering extension: *osquery.ExtensionManagerRegisterExtensionArgs. (0) field write error: write unix @->/opt/kubequery/osquery.em: write: broken pipe

goroutine 1 [running]:
main.main()
	/home/runner/work/kubequery/kubequery/cmd/kubequery/main.go:57 +0x489
```

**Comment by spasam** [comment]
Hmm! Tried with Docker Desktop on Mac with K8S. No luck.
```
spasam@Seshus-MacBook-Pro ~ % k logs kubequery-6b87cc45dd-vfqpz -n kubequery 
I0124 02:36:21.360683    52 interface.cpp:110] Registering extension (kubequery, 33929, version=, sdk=)
I0124 02:36:21.561676    11 events.cpp:867] Event publisher not enabled: BPFEventPublisher: Publisher disabled via configuration
I0124 02:36:21.561797    11 events.cpp:867] Event publisher not enabled: auditeventpublisher: Publisher disabled via configuration
I0124 02:36:21.561816    11 events.cpp:867] Event publisher not enabled: inotify: Publisher disabled via configuration
I0124 02:36:21.561828    11 events.cpp:867] Event publisher not enabled: syslog: Publisher disabled via configuration
I0124 02:37:26.602180    73 query.cpp:113] Storing initial results for new scheduled query: kubernetes_pod_security_policies
```

<img width="763" alt="Screen Shot 2021-01-23 at 9 42 19 PM" src="https://user-images.githubusercontent.com/438507/105619780-dfd1b300-5dc3-11eb-9443-7e3395349592.png">

**Comment by spasam** [comment]
Let me see what happens if I make the pod file system read-only. My guess is: it should crap out sooner if it cannot write to logs

**Comment by spasam** [comment]
If I make the container root file-system read-only, osqueryd fails when trying to create PID file, which makes sense. So something else is going on....

**Comment by spasam** [comment]
Not able to repro with increased extension timeouts. Feel free to re-open
